# Generated by Django 5.2.4 on 2025-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
